# Generated by Django 5.2 on 2025-04-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_content", models.TextField()),
                ("humanized_content", models.TextField()),
                ("detection_evasion", models.BooleanField(default=False)),
                ("plagiarism_check", models.BooleanField(default=False)),
                ("plagiarism_score", models.IntegerField(blank=True, null=True)),
                ("plagiarism_report_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
