# Generated by Django 5.2 on 2025-04-16 23:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanizer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("daily_limit", models.IntegerField(default=1000)),
                ("daily_count", models.IntegerField(default=0)),
                ("monthly_limit", models.IntegerField(default=10000)),
                ("monthly_count", models.IntegerField(default=0)),
            ],
        ),
    ]
