# Generated by Django 5.2 on 2025-04-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanizer", "0002_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
    ]
