# Generated by Django 5.2 on 2025-04-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanizer", "0003_submission_flagged"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
